#!/bin/bash
#rj queue=idle
#rj name=c768_204nodes
#rj io=1
#rj knl=1 
#rj nodes=204
#rj taskspernode=68
#rj runtime=5
#rj features=roce

###############################################################
# User defined variables

resolution=C768
export OMP_NUM_THREADS=4
ompi_flags="--bind-to core -map-by node --mca pml ucx -mca coll_hcoll_enable 1 -mca coll_hcoll_np 0"
domain=_0.0_0.0_13.125km
#domain=_135.0_-27.0_13.125km

###############################################################
# Set up the compute node environment 

module use /p9/dug/teamhpc/tests_for_candidate/markc/modulefiles
module load openmpi/4.0.5-hpcx-icc hdf5/1.10.7 netcdf/4.7.4 
export OMP_STACKSIZE=1g OMP_PLACES=cores OMP_PROC_BIND=close OMP_MAX_ACTIVE_LEVELS=3
ulimit -s unlimited


###############################################################
# Set up the working directory

work_dir=/p9/dug/teamhpc/sw/CCAMproject/work_${SLURM_NNODES}nodes

if [[ -d ${work_dir} ]]
then
   rm -rf ${work_dir}
fi

mkdir -p ${work_dir}
cd ${work_dir}
mkdir RESTART daily OUTPUT
cp /p9/dug/teamhpc/sw/CCAMproject/input_data/${resolution}/input${domain} ./input
ln -s /p9/dug/teamhpc/sw/CCAMproject/input_data/erai/ccam_eraint_200001.nc .


###############################################################
# Run the CCAM executable

/d/sw/hpc/bin/mpi_commtest
time mpirun -np $SLURM_NTASKS ${ompi_flags} /p9/dug/teamhpc/sw/CCAMproject/bin/globpea 
